### ISSUE TITLE
ICO Contracts

### ISSUE THREAD

**Issue by isysd** [isysd/io-http-iramiller.com#8]
+ [x] #11 ISYSD token issuance
 + [x] #12 Professional Flex redemption contract
 + [x] #13 3 Minute Selfie redemption contract
 + [x] #14 Advising guld redemption contract
 + [x] #15 30 Minute 1 Topic redemption contract
 + [x] #16 30 Minute 1 Topic Topless redemption contract
 + [x] #17 Speech redemption contract
 + [x] #18 shave my beard redemption contract
 + [x] #19 You shave my beard clause

**Comment by isysd** [comment]
Thanks for all of your excellent and hard work! The contracts look amazing, considering our timeline :+1:
